[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["graphql_service_sample"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/GraphQL","Category/Service","Internal/http"]
  name = "graphql_service_sample"
  org = "uvindradiasjayasinha"
  version = "3.1.0"

